spring.application.name=spring-boot-book-store
spring.datasource.url=jdbc:mysql://localhost:3306/book-store?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.servlet.context-path=/api

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
